<a href="https://colab.research.google.com/github/SallyPeter/gomycodeDSbootcamp/blob/main/Python/Checkpoint_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What You're Aiming For**

This ➡️ dataset contains loan information, including loan ID, customer gender, location, region, total price for each loan etc.


**Instructions**

 1. Begin by importing the necessary libraries, numpy.
 2. Use the open() function to open csv file and assign the result to a variable.
 3. Use the numpy array to perform some basic statistical analysis on the data, such as finding the mean, median, and standard deviation of the loan amounts.

**Note:**
- Be sure to close the file after you have finished reading it in with the open() function.
- Use the delimiter parameter in the genfromtxt() function to specify that the values in the file are separated by commas.
- You can use the numpy functions mean(), median(), and std() to find the mean, median, and standard deviation of the loan amounts.

In [1]:
# Begin by importing the necessary libraries, numpy.

import numpy as np

In [2]:
# Use the open() function to open csv file and assign the result to a variable.

f = open('Loan_prediction_dataset.csv')

f.readlines()

['Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status\n',
 'LP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y\n',
 'LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N\n',
 'LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y\n',
 'LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y\n',
 'LP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y\n',
 'LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y\n',
 'LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y\n',
 'LP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N\n',
 'LP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y\n',
 'LP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N\n',
 'LP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y\n',
 'LP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y\n',
 'LP001028,Male,Yes,2,Graduate,No,3073,8

In [3]:
# Use the numpy array to perform some basic statistical analysis on the data, such as finding the mean, median, and standard deviation of the loan amounts.

data = np.genfromtxt('Loan_prediction_dataset.csv', delimiter=',')

data

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ...,  1., nan, nan],
       [nan, nan, nan, ...,  1., nan, nan],
       ...,
       [nan, nan, nan, ...,  1., nan, nan],
       [nan, nan, nan, ...,  1., nan, nan],
       [nan, nan, nan, ...,  0., nan, nan]])

In [4]:
data = np.genfromtxt('Loan_prediction_dataset.csv', delimiter=',', dtype='int64', usecols=8, filling_values=0) # Loading only column 8 as it is the column containing the loan amounts.

data # Note np.genfromtxt converts str to either -1 or your filling value including the column headers.

array([  0,   0, 128,  66, 120, 141, 267,  95, 158, 168, 349,  70, 109,
       200, 114,  17, 125, 100,  76, 133, 115, 104, 315, 116, 112, 151,
       191, 122, 110,  35, 120, 201,  74, 106, 114, 320,   0, 100, 144,
       184, 110,  80,  47,  75, 134,  96,  88,  44, 144, 120, 144, 100,
       120, 112, 134, 286,  97,  96, 135, 180, 144, 120,  99, 165,   0,
       116, 258, 126, 312, 125, 136, 172,  97,  81,  95, 187, 113, 176,
       110, 180, 130, 111,   0, 167, 265,  50, 136,  99, 104, 210, 175,
       131, 188,  81, 122,  25,   0, 137,  50, 115, 131, 133, 151,   0,
         0, 160, 100, 225, 120, 216,  94, 136, 139, 152,   0, 118, 185,
       154,  85, 175, 259, 180,  44, 137,  81, 194,  93, 370,   0, 160,
       182, 650,  74,  70,  25, 102, 290,  84,  88, 242, 129, 185, 168,
       175, 122, 187, 100,  70,  30, 225, 125, 118, 152, 244, 113,  50,
       600, 160, 187, 120, 255,  98, 275, 121, 158,  75, 182, 112, 129,
        63, 200,  95, 700,  81, 187,  87, 116, 101, 495, 116, 10

In [5]:
data = np.delete(data, 0) # removing the column header which is the first entry in the array.
data

array([  0, 128,  66, 120, 141, 267,  95, 158, 168, 349,  70, 109, 200,
       114,  17, 125, 100,  76, 133, 115, 104, 315, 116, 112, 151, 191,
       122, 110,  35, 120, 201,  74, 106, 114, 320,   0, 100, 144, 184,
       110,  80,  47,  75, 134,  96,  88,  44, 144, 120, 144, 100, 120,
       112, 134, 286,  97,  96, 135, 180, 144, 120,  99, 165,   0, 116,
       258, 126, 312, 125, 136, 172,  97,  81,  95, 187, 113, 176, 110,
       180, 130, 111,   0, 167, 265,  50, 136,  99, 104, 210, 175, 131,
       188,  81, 122,  25,   0, 137,  50, 115, 131, 133, 151,   0,   0,
       160, 100, 225, 120, 216,  94, 136, 139, 152,   0, 118, 185, 154,
        85, 175, 259, 180,  44, 137,  81, 194,  93, 370,   0, 160, 182,
       650,  74,  70,  25, 102, 290,  84,  88, 242, 129, 185, 168, 175,
       122, 187, 100,  70,  30, 225, 125, 118, 152, 244, 113,  50, 600,
       160, 187, 120, 255,  98, 275, 121, 158,  75, 182, 112, 129,  63,
       200,  95, 700,  81, 187,  87, 116, 101, 495, 116, 102, 18

In [6]:
np.size(data)

614

In [7]:
# Use the numpy array to perform some basic statistical analysis on the data, such as finding the mean, median, and standard deviation of the loan amounts.

mean_data = np.mean(data)
print(f'The mean loan amount is {mean_data}')

The mean loan amount is 141.16612377850163


In [8]:
med_data = np.median(data)
print(f'The median loan amount is {med_data}')

The median loan amount is 125.0


In [9]:
std_data = np.std(data)
print(f'The stand deviation of the loan amount is {std_data}')

The stand deviation of the loan amount is 88.2686624330009


In [10]:
max_data = np.max(data)
print(f'The maximum loan amount is {max_data}')

The maximum loan amount is 700


In [11]:
min_data = np.min(data)
print(f'The minimum loan amount is {min_data}')

The minimum loan amount is 0
