<a href="https://colab.research.google.com/github/SallyPeter/gomycodeDSbootcamp/blob/main/Python/Shambhus_python_for__Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Python for Data Analysis
### Below are the important libraries available in python
* Numpy
* Pandas
* Matplotlib
* Seaborn

In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
# Creating an Array in Numpy

my_array = np.array([34,23,12,32,45,65,54])

In [ ]:
my_array

array([34, 23, 12, 32, 45, 65, 54])

In [ ]:
print(my_array)

[34 23 12 32 45 65 54]


In [ ]:
print(type(my_array))

<class 'numpy.ndarray'>


In [ ]:
zero_dim = np.array(3)

In [ ]:
np.ndim(zero_dim)

0

In [ ]:
np.ndim(my_array)

1

In [ ]:
two_dim = np.array([[12,23,34], [21,45,61]])
np.ndim(two_dim)

2

In [ ]:
two_dim.shape

(2, 3)

In [ ]:
three_dim = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(np.ndim(three_dim))
print(three_dim.shape)
print(three_dim.size)

3
(2, 2, 3)
12


In [ ]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
d = [10,11,12]

e = np.array([a,b])
f = np.array([c,d])

h = np.array([e,f])

In [ ]:
print(np.ndim(h))
print(h.shape)
print(h.size)

3
(2, 2, 3)
12


## Accessing the Elements of an Array

In [ ]:
my_array

array([34, 23, 12, 32, 45, 65, 54])

In [ ]:
my_array[0]

34

In [ ]:
my_array[0:5:2]

array([34, 12, 45])

In [ ]:
two_dim

array([[12, 23, 34],
       [21, 45, 61]])

In [ ]:
# two_dim[x,y]
two_dim[0,0]

12

In [ ]:
two_dim[0][0]

12

In [ ]:
two_dim[0:2,0:2]

array([[12, 23],
       [21, 45]])

In [ ]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
three_dim[0][0][0]

1

In [ ]:
three_dim[1][0][1] = 65

In [ ]:
three_dim[1][1][0]

10

In [ ]:
three_dim[0:2,0:2,1]

array([[ 2,  5],
       [ 8, 11]])

In [ ]:
three_dim[0:2,1:2,2]

array([[ 6],
       [12]])

In [ ]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7, 65,  9],
        [10, 11, 12]]])

In [ ]:
three_dim[0][1] = three_dim[1][0]

In [ ]:
three_dim

array([[[ 1,  2,  3],
        [ 7, 65,  9]],

       [[ 7, 65,  9],
        [10, 11, 12]]])

In [ ]:
three_dim.shape

(2, 2, 3)

In [ ]:
three_dim.reshape(1,3,4)

array([[[ 1,  2,  3,  7],
        [65,  9,  7, 65],
        [ 9, 10, 11, 12]]])

In [ ]:
three_dim.reshape(12)

array([ 1,  2,  3,  7, 65,  9,  7, 65,  9, 10, 11, 12])

In [ ]:
empty_array = np.empty([2,3])

In [ ]:
empty_array.round(2)

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 8.94213159e+130, 7.19361053e+140]])

In [ ]:
zero_array = np.zeros([3,4])
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
one_array = np.ones([3,4])
one_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
full_array = np.full([3,4], 'Davids')
full_array

array([['Davids', 'Davids', 'Davids', 'Davids'],
       ['Davids', 'Davids', 'Davids', 'Davids'],
       ['Davids', 'Davids', 'Davids', 'Davids']], dtype='<U6')

In [ ]:
three_dim

array([[[ 1,  2,  3],
        [ 7, 65,  9]],

       [[ 7, 65,  9],
        [10, 11, 12]]])

In [ ]:
like_array = np.empty_like(three_dim)
like_array

array([[[4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408]],

       [[4607182418800017408, 4607182418800017408, 4607182418800017408],
        [4607182418800017408, 4607182418800017408, 4607182418800017408]]])

In [ ]:
zeros_like_array = np.zeros_like(three_dim)
zeros_like_array

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
arrange_array = np.arange(11,21,.5, dtype = float)
arrange_array

array([11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(np.mean(x, axis=1))

[[1 2 3]
 [4 5 6]]
[2. 5.]


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(np.mean(x, axis=0))

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]
